### ISSUE TITLE
Vocabulary module does not have an option for timeout

### ISSUE THREAD

**Issue by natefanaro** [blissend/hqtrivia-automation#2]
https://github.com/blissend/hqtrivia-automation/blob/master/hqtrivia-automation.py#L64

`timeout` is not implemented in `tasdikrahman/vocabulary` I noticed the issue you raised here https://github.com/tasdikrahman/vocabulary/issues/60 and am guessing there is a custom version of vocabulary floating around (but wasn't publicly forked)

For now removing `timeout` works, but the script is too slow without it.

**Comment by blissend** [comment]
Yes, I just ended up editing my local vocabulary for timeouts. Then I made it use nltk (local dictionary) first before using vocabulary (online dictionary). In the next update each lookup will be in its own process/thread rather than each answer to speed things up even more.

I will make sure to remove what you pointed out until vocabulary has this in officially.
